### ISSUE TITLE
NeoGPS::Location_t::RAD_PER_DEG' cannot appear in a constant-expression

### ISSUE THREAD

**Issue by shrikantbarve** [SlashDevin/NeoGPS#6]
Hello,

I am facing the issue while compiling on Arduino IDE. Here is exact error message >>

```
In file included from C:\Users\abc\Documents\Arduino\libraries\NeoGPS-master/GPSfix.h:34:0,
                 from C:\Users\abc\Documents\Arduino\libraries\NeoGPS-master/NMEAGPS.h:28,
                 from neogps_neoswserial.ino:1:
C:\Users\abc\Documents\Arduino\libraries\NeoGPS-master/Location.h:57:52: error: 'NeoGPS::Location_t::RAD_PER_DEG' cannot appear in a constant-expression
     CONST_CLASS_DATA float DEG_PER_RAD     = 1.0 / RAD_PER_DEG;
                                                    ^
Error compiling.
```

**Comment by SlashDevin** [comment]
It's probably because you put NeoGPS in the Libraries/NeoGPS-master subdirectory.  They are supposed to go in your sketch directory.

**Comment by shrikantbarve** [comment]
Hello,

Still it is not working, here is my directory structure >>

![image](https://cloud.githubusercontent.com/assets/19504442/18199325/6dc86cbe-711d-11e6-9ff7-f48873cb0851.png)


Once I click on Verify button, still it is giving me the same error:

![image](https://cloud.githubusercontent.com/assets/19504442/18199376/99bed81c-711d-11e6-8cfe-7e318dcbaa32.png)

**Comment by shrikantbarve** [comment]
I followed Steps at

https://github.com/SlashDevin/NeoGPS/blob/master/doc/Installing.md

but still getting same error please find screenshots:

![image](https://cloud.githubusercontent.com/assets/19504442/18199742/5713bec2-711f-11e6-98ea-e15313ffa72b.png)

![image](https://cloud.githubusercontent.com/assets/19504442/18199751/62220648-711f-11e6-9a2d-894f27129d74.png)

I am totally clueless :-(

**Comment by shrikantbarve** [comment]
I was using Arduino 1.6.5 and after upgrading to 1.6.11 which is the current one as of now, it has successfully compiled.

**Comment by SlashDevin** [comment]
I see.  It was a very obscure problem in that version of the IDE.  I have made a change to work around it in 1.6.5.

Thanks!
